query GetCustomerData {
	customer {
		...CustomerBase
		orders {
			nodes {
				id
				date
				orderNumber
				total
				status
				lineItems {
					nodes {
						databaseId
					}
				}
			}
		}
	}
}
