fragment OrderProductBase on Order {
  id
  date
  orderNumber
  total
  status
  lineItems {
    nodes {
      quantity
      total
      product {
        node {
          ...SimpleProductFragment
          ...VariableProductFragment
        }
      }
    }
  }
}
